### ISSUE TITLE
global information is not used when no groups are defined

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/springboot-swagger-starter#19]
when I do

```
swagger:
  apiInfo:
    title: Some Title
    description: my description
```

and do not define docket groups, the information displayed on the swagger Ui start page does not have the title/description/version data.

Guess: when no groups are found, the apiInfo block is not used.
